rubytoolbox/rubytoolbox

.travis.yml
Gemfile
Gemfile.lock
Procfile
config.ru

Heroku is sponsoring hosting for the future Ruby Toolbox :fireworks: :rocket: :rainbow:
This PR adds deployment of the master branch to heroku using Travis CI.
It also adds rack middlewares for enforcing the canonical domain as well as TLS.

Set up deployment to Heroku via Travis

---

.travis.yml
Gemfile
Gemfile.lock
config/application.rb
config/environments/production.rb

A bunch of ops tidbits:
* Set rails logger to info in production (*that default of `debug` is surprising...*)
* Use logstash json_event formatter for better log analytics
* ~~Move Heroku deploy API key from `.travis.yml` to travis env (keeping it encrypted) - this adds an extra layer of protection in case Travis' private key is leaked, and also makes it easier to change down the line~~ Turns out this is much harder to achieve than I thought... I could not figure out from neither Travis docs nor github code search how to set this up appropriately - maybe was using `travis encrypt` wrong, but I tried many variants. Will need to follow up with travis support.

Operations tidbits

---

.rubocop.yml
Gemfile
Gemfile.lock
app/jobs/rubygem_info_job.rb
app/jobs/rubygem_update_job.rb
app/jobs/rubygems_sync_job.rb
app/models/rubygem.rb
app/services/http_service.rb
config/application.rb
config/http_mock_responses.yml
db/migrate/20171230223928_create_rubygems.rb
db/structure.sql
spec/cassettes/rspec.yml
spec/cassettes/unknown_gem.yml
spec/integration/rubygem_update_spec.rb
spec/jobs/rubygem_update_job_spec.rb
spec/jobs/rubygems_sync_job_spec.rb
spec/rails_helper.rb
spec/services/http_service_spec.rb

Following #45, this adds a rubygems db model and background jobs for syncing the general rubygems index itself as well as individual gem info from the rubygems API to the local mirror. 
It also adds basic facilities for unit and integration testing of things that interact with http - in unit specs, the data is fetched from a static yaml file for easy control over the test environment for unit tests, and fuller-stack integration specs should use real HTTP, backed by VCR and webmock.
Next up:
* Link project and rubygem models in the DB
* Detect github repository from gem's urls and set it on the project
* Fetch github repo data
* Calculate scores
* Add actual stats to the beta UI
* Ship it

Rubygem info import

---

config/http_mock_responses.yml
spec/integration/rubygem_update_spec.rb
spec/jobs/rubygem_update_job_spec.rb

Oops, I forgot to push this final commit in #47 :confetti_ball:

Pull 'rubygems is down' case from integration to unit spec

---

app/assets/stylesheets/application.css.sass
app/views/categories/show.html.slim
yarn.lock

This changes the display of stats on mobile from 
to
* Also fixes some mistaken margin on the stats row label
* Also upgrades https://bulma.io/

Improve responsiveness of project stats on mobile

---

app/jobs/project_update_job.rb
app/jobs/rubygem_update_job.rb
app/models/github.rb
app/models/project.rb
app/models/rubygem.rb
db/migrate/20180103193038_add_gem_and_repo_to_projects.rb
db/migrate/20180103194335_add_check_constraint_on_project_gem_reference.rb
db/structure.sql
spec/jobs/project_update_job_spec.rb
spec/jobs/rubygem_update_job_spec.rb
spec/models/github_spec.rb
spec/models/project_spec.rb
spec/rails_helper.rb

This adds references between the shallow projects table and rubygems as added via #47 
It also prepares github repo references, detecting them from the gem's URLs on the fly.

Rubygems to Projects

---

app/services/cron.rb
lib/tasks/cron.rake
spec/services/cron_spec.rb

For now it only sets in motion the Rubygems index sync task introduced in #47

Add a basic cron task

---

app/services/cron.rb
spec/services/cron_spec.rb

Following #53, this forwards cron exceptions to Appsignal

Report cron errors to appsignal

---

app/jobs/rubygem_update_job.rb
app/jobs/rubygems_sync_job.rb
app/jobs/rubygems_update_scheduler_job.rb
app/models/rubygem.rb
app/services/cron.rb
spec/jobs/rubygems_update_scheduler_job_spec.rb
spec/models/rubygem_spec.rb
spec/services/cron_spec.rb

This builds upon #47 and #53 and adds daily updates of rubygem info from the rubygems.org API via sidekiq

Schedule daily updates of rubygem info

---

app/jobs/rubygem_update_job.rb
spec/jobs/rubygem_update_job_spec.rb

This fixes an oversight in #55, in that gems that didn't change at all since the last update would obviously also not get an updated_at change by active record, and hence keep cropping up in the update schedule every hour. This adds an explicit updated_at timestamp on the update job which should fix this issue.

Touch rubygems on update to track what's been fetched

---

app/jobs/project_score_job.rb
app/jobs/project_update_job.rb
app/models/category.rb
app/models/project.rb
app/views/categories/show.html.slim
db/migrate/20180104223026_add_score_to_projects.rb
db/structure.sql
spec/cassettes/full-project-sync-from-gem.yml
spec/cassettes/full-project-sync-from-github.yml
spec/integration/project_sync_spec.rb
spec/jobs/project_score_job_spec.rb
spec/jobs/project_update_job_spec.rb
spec/models/project_spec.rb
spec/rails_helper.rb

Now that the data for rubygems (#47 and following) and github repos (#59) is being synced, we need a way to display projects by popularity - this PR adds that. The calculation is the same as used on the old ruby toolbox site. This might change later on, but for the time being, let's stick to what's tried and tested :)

Project scores

---

.travis.yml
Gemfile
Gemfile.lock
app/models/project.rb
spec/features/category_display_spec.rb

Bugfix following #61 - I forgot to add a delegation for the watchers_count, and no tests covered that bit yet. Hence, this adds an rspec feature spec that makes that request and would have failed.

Add basic request spec for display of projects

---

app/assets/stylesheets/application.css.sass
app/controllers/projects_controller.rb
app/models/category.rb
app/models/project.rb
app/views/categories/show.html.slim
app/views/projects/_metrics.html.slim
app/views/projects/show.html.slim
config/routes.rb
lib/patterns.rb
spec/controllers/categories_controller_spec.rb
spec/controllers/projects_controller_spec.rb
spec/routes/project_routes_spec.rb

This adds a very basic page for each project. This can later be expanded to hold further details in addition to what is already shown in category (and later search) overview listings

Add project details pages

---

app/jobs/catalog_import_job.rb
app/services/catalog_import.rb
app/services/cron.rb
spec/jobs/catalog_import_job_spec.rb
spec/services/catalog_import_spec.rb
spec/services/cron_spec.rb

This adds a background job for fetching the [catalog](https://github.com/rubytoolbox/catalog) and syncing it up with the local db. It's scheduled for an hourly cron run.
At a later point, this shall be converted to a webhook whenever the catalog actually changed. The job itself can remain untouched, only the cron job would be superseded by that.

Cron job for syncing catalog

---

app/assets/stylesheets/application.css.sass

This must have slipped in via a recent update of the bulma package. Notice how the "Popularity" label to the left is not vertically aligned with the numbers to the right.

Fix a minor glitch in metric row label positioning

---

app/helpers/application_helper.rb
app/views/categories/show.html.slim
spec/helpers/application_helper_spec.rb

Fixes #115 and references #116 
I opted for the easy helper-method solution instead of defaulting the description via AR getter override as in
```ruby
def description
self[:description] || "No description yet"
end
```
since it rightfully violated the CatalogImport spec and would consequently block any operations on Categories with empty description in the future

Show Category description

---

app/controllers/categories_controller.rb
app/controllers/projects_controller.rb
app/models/category.rb
app/models/project.rb
db/migrate/20180221214013_change_categories_and_github_repo_primary_keys_to_citext.rb
db/structure.sql
spec/controllers/categories_controller_spec.rb
spec/controllers/projects_controller_spec.rb

See also #146 and #104
Once this is done, maybe all category permalinks in the catalog should be unified to lowercase writing

Convert primary keys to case-insensitive text where applicable

---

app/views/welcome/home.html.slim

Drops the welcome page blog post / release announcement added in #124, keeping the markup for possible future announcements :)

Drop release announcement hero from startpage

---

app/graphql-queries/github/repo.erb
app/graphql-queries/github/repo.graphql
app/jobs/github_repo_update_job.rb
app/services/github_client.rb
app/services/github_client/repository_data.rb
app/services/http_service.rb
db/migrate/20180322231205_drop_outdated_github_columns.rb
db/migrate/20180322231848_add_new_github_columns.rb
db/structure.sql
spec/cassettes/full-project-sync-from-gem.yml
spec/cassettes/full-project-sync-from-github.yml
spec/cassettes/graphql/carrierwave.yml
spec/cassettes/graphql/fails.yml
spec/cassettes/graphql/rails.yml
spec/cassettes/rails/rails.yml
spec/cassettes/rails/unknown_repo.yml
spec/cassettes/thread_safe_gem.yml
spec/cassettes/unknown_gem.yml
spec/fixtures/graphql_responses/github/rails.json
spec/integration/github_client_spec.rb
spec/jobs/github_repo_update_job_spec.rb
spec/rails_helper.rb

This replaces #83
The query shown here is rated as 1 against the hourly 5k limit as it stands, and it conveys a whole lot more information, i.e. open/closed ratios, total amounts and commit frequency (see #77)
Downsides: 
* You need a valid OAuth API bearer token to use this at all (in contrast to the limited, but functional 60 requests per hour on github REST)
* No HTTP caching via e-tag or similar. Since most of the requests made against the API via the daily sync actually are in vein (nothing has changed at all), caching could really help to save some rate limit points
* No README endpoint
* No stats endpoint (see #93)
This should end up replacing the current way of syncing github stats.
The API call is simple enough:
```ruby
query = …
```

Convert to GitHub graphql API

---

README.md
app/helpers/application_helper.rb
app/models/github.rb
app/models/github_repo.rb
app/models/project.rb
app/services/github_client.rb
app/views/categories/show.html.slim
app/views/projects/_metric.html.slim
app/views/projects/_metrics.html.slim
app/views/projects/show.html.slim
spec/helpers/application_helper_spec.rb
spec/models/github_repo_spec.rb
spec/models/github_spec.rb
spec/services/github_client_spec.rb

Further Github GraphQL integration

---

config/appsignal.yml

There's a few legacy routes for projects and quite frequently some weird invalid permalinks coming in from crawlers etc, and they always cause an exception notification on appsignal. Since the `ActiveRecord::RecordNotFound` is used for regular 404 triggering, this does not represent an exceptional situation and should just be handled gracefully - hence, we ignore it.
This also adds the default app name for appsignal to the yml config, which makes it one less thing to configure when setting up a new deployment.

Ignore common exceptions from showing up in appsignal

---

app/jobs/github_repo_update_job.rb
app/models/github.rb
app/models/github_ignore.rb
app/services/cron.rb
app/services/github_client/repository_data.rb
db/migrate/20180718195202_create_github_ignores.rb
db/structure.sql
spec/jobs/github_repo_update_job_spec.rb
spec/models/github_ignore_spec.rb
spec/models/github_spec.rb
spec/services/cron_spec.rb

Following on #245 this deals with a bunch of common issues when syncing repos from github based on the repo reference found in the rubygem links:
* Sometimes the reference has `.git` appended, which leads to a bunch of interesting problems in [conjunction with Githubs GraphQL API](https://platform.github.community/t/repository-redirects-in-api-v4-graphql/4417)
* Some repos are plain and simply gone without any futher notice
* Some repos are referenced from a gem, yet empty
Most notably, for 100% gone 404 repos this puts the repo on an ignore list for 2 weeks, ensuring that it will not pollute github with unneccessary requests. It also drops the `.git` part at the end of detected repo urls, and ensures the sync does not crash if there are no commits on the repo at all.
I could not find …

Fix common github sync issues

---

app/jobs/rubygems_sync_job.rb
spec/jobs/rubygems_sync_job_spec.rb

Based on my finding noted in https://github.com/rubytoolbox/catalog/pull/165
The way ruby toolbox was fetching the remote gem specs so far had a blind spot: Gems that have only prerelease versions available were not indexed. This PR changes that, so a whole bunch of gems that have not been available on the toolbox should start showing up after this is merged and deployed.

Index gems with only pre-release versions as well

---

README.md
app/views/layouts/application.html.slim

Since I will be spending proper desk time through december and january working on this, it makes sense to have a community chat room at least for this time (usually I don't set up this kind of thing because of the obvious problems of several-day lag in chat communications ;) 
What I like in particular about gitter is that you login solely with your github account, and the channel can also be read without logging in publicly.
Since github announced this week they have acquired a product named spectrum (https://spectrum.chat), I also took a brief look at that. It seems very similar to https://twist.com/, however I would prefer to keep longer, feature-specific discussion on github issues and "just" use the chat for a more generic, low-barrier entrypoint for questions and discussions.
My …

Add links to gitter community chatroom

---

app/jobs/remote_update_scheduler_job.rb
app/models/github_repo.rb
spec/jobs/remote_update_scheduler_job_spec.rb
spec/models/github_repo_spec.rb

I'm seeing a whole lot of failing github syncs due to invalid repo references on Appsignal. Basically this is a consequence of #246, where I added a fix to drop `.git` suffixes from gem's github repo refs because they break with graphql queries. Since we subsequently create a new db record with that adjusted repo path `foo/bar` permalink, the old `foo/bar.git` repo remained. Since we perform data sync on all github repo db records recurringly, these repos now get stuck in sad sidekiq retry hell ad infinitum. This should fix that problem.

Destroy orphaned github repo records

---

app/services/github_client.rb
app/services/github_client/repository_data.rb
spec/cassettes/github/org_reference.yml
spec/cassettes/graphql/empty.yml
spec/integration/github_client_spec.rb

* Some repo refs picked from rubygems reference `orgs/foobar`, which, if the org exists, redirects to the organization of said name, leading to a `NoMethodError "split"` on the redirect location target
* Some repo refs picked from rubygems point at empty repos... The repository data parser was choking when passing `nil` for the last `pushedAt` to `Time.parse` in those cases

Bugfixes for github sync edge cases

---

app/jobs/catalog_import_job.rb
app/jobs/category_ranking_job.rb
app/models/category.rb
db/migrate/20181210092238_add_rank_to_categories.rb
db/structure.sql
spec/jobs/catalog_import_job_spec.rb
spec/jobs/category_ranking_job_spec.rb
spec/models/category_spec.rb

This adds a background job to identify and rank the "most popular" categories. After some experimentation I settled on ranking categories based on the two most popular projects in the category, as this prevents categories that only really have one highly popular library from being overemphasized in the ranking. The method applied here produced (*imho*) reasonable results, as of the time being:
* [Web App Frameworks](https://www.ruby-toolbox.com/categories/web_app_frameworks)
* [JSON Parsers](https://www.ruby-toolbox.com/categories/JSON_Parsers)
* [Scripting Frameworks](https://www.ruby-toolbox.com/categories/scripting_frameworks)
* [Test Frameworks](https://www.ruby-toolbox.com/categories/testing_frameworks)
* [Template Engines](https://www.ruby-toolbox.com/categories/template_engines)
* …

Rank popular categories

---

.env.test
.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/webhooks/github_controller.rb
config/routes.rb
spec/controllers/webhooks/github_controller_spec.rb

Adds an endpoint at `POST /webhooks/github` for receiving github page build notifications. This enables syncing [the catalog](https://github.com/rubytoolbox/catalog) on every update right away instead of waiting for the hourly cron to kick in.

Github catalog update webhook endpoint

---

app/controllers/webhooks/github_controller.rb
spec/controllers/webhooks/github_controller_spec.rb

Followup to #339 because that approach did not do the trick yet.
It seems that github only emits the `page_build` event on "native" builds from GH pages. However, the [toolbox's catalog](https://github.com/rubytoolbox/catalog) runs some simple ruby code on Travis CI, then does a manual deployment to github pages.
To circumvent this problem this PR switches over to listen for successful CI status events from github on the default branch of the repo.

Listen to github CI status instead of page build event for catalog update

---

Procfile
app/controllers/webhooks/github_controller.rb
app/jobs/catalog_import_job.rb
spec/controllers/webhooks/github_controller_spec.rb

This is getting embarrassing... Another followup to #339 and #341. I had overlooked that the `branches` key in the github payload actually contains an array of branches, not a single hash. This fixes that and finally makes this work.
I also introduced a "priority" queue in sidekiq that the catalog import gets placed on, otherwise if we have a huge number of recurring stats fetch jobs in the queue the "instant" sync is not so instant anymore :)

Adjust for actual expected github webhook payload

---

app/assets/stylesheets/application.css.sass
package.json
yarn.lock

This PR upgrades [Bulma](https://bulma.io/documentation/), the css framework used for the Ruby Toolbox, from 0.6.1 to the latest 0.7.2
I also decided to do away with the individual imports, they are quite cumbersome since on upgrades they sometimes make stuff break and if I want to use a different part of the framework I have to hunt down the correct file, while the gain is quite negligible: 38kb before, 50kb after gzipped, and I still need to import some additional components like the responsive main menu, so let's just keep it simple here...

Upgrade Bulma, import all of it

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css.sass
app/helpers/application_helper.rb
app/views/layouts/application.html.slim
spec/features/mobile_navigation_spec.rb
spec/helpers/application_helper_spec.rb
spec/rails_helper.rb

This converts the current, custom top navigation bar to a proper [Bulma navbar](https://bulma.io/documentation/components/navbar/)
Before:
After:
This will allow for some actual navigation links to point to things in the top bar. It also features the usual mobile hamburger:
Since this is the first time some actual javascript code is added to the site I added a very basic test using chrome headless, including setting up the little tidbits of wiring to make it work.

Navigation Menu

---

app/assets/javascripts/application.js

I didn't pay attention - the bulma snippet for the hamburger introduced in #347 uses ES2015+ features, and since we don't use any javascript except for rails' ujs and turbolinks so far I think it's not worth it to go all in on webpacker/babel js compilation. Therefore, this PR converts it to old-school JS (via [babel's online REPL](https://babeljs.io/repl) ;)
[The error that happened on deployment of master to Heroku](https://travis-ci.org/rubytoolbox/rubytoolbox/builds/466477957) was:
```
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.38s.
rake aborted!
Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true). …
```

Do not use 'new' javascript stuff

---

app/assets/stylesheets/application.css.sass
app/views/layouts/application.html.slim
app/views/welcome/home.html.slim

* Fixes a minor glitch on the new navbar via #347 where the subtle border did not stretch across the entire window anymore
* There was an extra padding on the left and right of the category listing page due to the wrong order of section and container elements, leading it to not be aligned with the header and footer sides
* In tablet view the responsive wrapping of the columns did not work correctly, leading to arbitrary column widths and overflowing text
* Updates the SVG main logo to have the same whitespace on top as on the bottom, leading to vertical alignment across the header bar
Before & After:

Minor UI tweaks

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css.sass
app/assets/stylesheets/components/category_card.sass
app/helpers/application_helper.rb
app/views/categories/_list.html.slim
app/views/components/_category_card.html.slim
app/views/components/_component_example.html.slim
app/views/layouts/application.html.slim
app/views/pages/components.html.slim
app/views/pages/components/category_card.html.slim
app/views/projects/_project.html.slim
app/views/projects/show.html.slim
app/views/searches/show.html.slim
app/views/welcome/home.html.slim
spec/features/styleguide_spec.rb

This PR introduces new, unified category card component. 
It also marks the beginning of an effort to clean up and unify styling across the site into reusable components to get rid of the current, chaotic sprinkles of bulma-specific CSS classes within the views.
To that end, this card is used via a simple helper that calls the underlying partial.
This PR also introduces a very simple "living styleguide" to document, showcase and test components and their intended use in isolation. After deploy, the page will be available via https://www.ruby-toolbox.com/pages/components
The styleguide is rendered using the [high_voltage gem](https://github.com/thoughtbot/high_voltage), which is also newly introduced here. The gem will also be used for the upcoming docs/guides section.
The new card …

UI: Category Cards & Living Styleguide

---

Gemfile
Gemfile.lock
app/models/category.rb
app/views/pages/components/category_card.html.slim
spec/models/category_spec.rb

Followup to #350 - since we now also show a the top project names on the category search result cards they should be eager loaded.

Eager-load projects for categories on search

---

app/models/category.rb
db/migrate/20181213102703_add_category_description_ts_vector.rb
db/structure.sql
spec/models/category_spec.rb

This increases findability of categories since we're not limited to just the words in the name, but also to the wider keyword namespace provided by the description. Example: Searching for "web application" or "web development" did not find the web app frameworks category before, now it does.
Maybe to further expand on this it would be helpful to also maintain some "hidden" keywords that apply to the search, but first lets see how this goes and focus on providing good descriptions for all categories that contain some reasonable search words inside the description itself

Include category descriptions in full text search

---

.rubocop.yml
app/assets/stylesheets/application.css.sass
app/assets/stylesheets/components/project_health_tag.sass
app/helpers/application_helper.rb
app/models/github_repo.rb
app/models/project.rb
app/models/project/health.rb
app/models/project/health/checks.rb
app/views/components/_project_health_tag.html.slim
app/views/pages/components/project_health_tag.html.slim
app/views/projects/_project.html.slim
app/views/projects/show.html.slim
config/locales/en.yml
spec/models/project/health/checks_spec.rb
spec/models/project/health_spec.rb

Detection of unmaintained projects came in highest in the recent [community survey](https://www.ruby-toolbox.com/blog/2018-12-04/survey-results).
This PR adds project health checks to make it easier to make a quick assessment of the maintenance status of a project.
See [checks.rb](https://github.com/rubytoolbox/rubytoolbox/blob/536d73f3c66f9e36b67dc7701ef24cbb44333de2/app/models/project/health/checks.rb) for the currently defined checks. For starters it's mostly about commit and release activity, hopefully over time we can add a few more of these.
The assessments have 3 levels: Green, yellow and red, depending on the status. 
* For red I picked a timeframe of 3 years (no gem release in 3 years, no commits in 3 years)
* For yellow it's 1 year of inactivity
Let's see how this goes. From a …

Project health checks and display

---

config/locales/en.yml

On mobile these two labels for #355 were a bit too long, making them break out of their container. Also, the specific "5 years" for long-lived projects could give the wrong impression that the project was exactly 5 years old, so I generalized that as well.
I looked into making the label text wrap into multiple lines, but this is not currently supported by the Bulma framework, and rolling our own seems a bit excessive considering that we use the tag addons for the icon and both would need to grow in height in sync. It's probably a good idea to have the text concise anyway :)

Shorten long health labels to avoid breaking container on mobile

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.css.sass
app/views/layouts/application.html.slim
doc/configuration.md
package.json
spec/features/mobile_navigation_spec.rb
spec/rails_helper.rb
yarn.lock

This PR makes the top nav sticky / floating. Toolbox pages tend to be long if there's a lot of projects, so this should make it a bit easier to navigate. Also, with #347 and upcoming new nav items the top bar is becoming a bit more than just a place to put the logo / search button into, so making it always visible also makes more sense now in that regard as well.

Sticky top navigation

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/project_order_dropdown.sass
app/controllers/categories_controller.rb
app/controllers/searches_controller.rb
app/helpers/application_helper.rb
app/models/category.rb
app/models/project.rb
app/models/project/order.rb
app/models/search.rb
app/views/categories/show.html.slim
app/views/components/_project_order_dropdown.html.slim
app/views/pages/components/project_order_dropdown.html.slim
app/views/projects/_metric.html.slim
app/views/projects/_project.html.slim
app/views/projects/show.html.slim
app/views/searches/show.html.slim
config/locales/en.yml
spec/controllers/categories_controller_spec.rb
spec/controllers/searches_controller_spec.rb
spec/features/category_display_spec.rb
spec/features/mobile_navigation_spec.rb
spec/features/search_spec.rb
spec/integration/i18n_spec.rb
spec/models/project/order_spec.rb
spec/models/project_spec.rb
spec/models/search_spec.rb
spec/rails_helper.rb
spec/support/factories.rb

This is another feature that [was requested a lot in the community survey](https://www.ruby-toolbox.com/blog/2018-12-04/survey-results)
This PR introduces custom sorting of project listings based on other metrics than the score, also making use of the cleanups made in #359.
Todos:

Custom project list ordering

---

Gemfile
Gemfile.lock
app/controllers/searches_controller.rb
app/models/project.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/searches/show.html.slim
config/initializers/kaminari_config.rb
config/locales/en.yml
spec/controllers/searches_controller_spec.rb
spec/features/mobile_navigation_spec.rb
spec/features/search_spec.rb
spec/rails_helper.rb
spec/support/factories.rb
spec/support/helpers/feature_spec_helpers.rb

This PR finally introduces pagination of project search results. So far, the total result list was hard-limited to 25 projects (see also #109). With this change it becomes possible to browse the entire result set.

Search results pagination

---

app/assets/javascripts/application.js
app/views/searches/show.html.slim
spec/features/search_spec.rb
spec/support/helpers/feature_spec_helpers.rb

Some minor search UI tweaks remaining from #109 to allow closing that one:
* Improved "blank search" page - also show the search input at full width on desktop now
* Auto-focus the search input on the search page
* Put the submit button into loading state on submit to give visual feedback

Search UI tweaks

---

app/jobs/project_score_job.rb
app/models/github_repo.rb
app/models/project.rb
app/models/project/fork_detector.rb
db/migrate/20190110202221_add_bugfix_fork_data_to_projects.rb
db/structure.sql
spec/jobs/project_score_job_spec.rb
spec/models/github_repo_spec.rb
spec/models/project/fork_detector_spec.rb
spec/models/project_spec.rb
spec/support/factories.rb

This PR adds a mechanism for detecting "bugfix forks" as part of an effort to improve search result relevance over the next weeks.
There is a huge number of namespaced gems that only have one or maybe a handful of releases, long in the past. Quite frequently they still reference the upstream github repo, so their popularity score is very high for popular gems.
The reason for their existence usually is the trouble that was deploying hotfixed libraries with your app before bundler made including gems from github repos a breeze (thank you bundler, this is so helpful :). 
Since you could not simply send a PR with an urgent fix upstream and go with your github branch for a while, many people resorted to the practice of sending a PR and issuing a hotfixed, namespaced gem to github until the PR …

Bugfix fork detection

---

app/assets/javascripts/application.js
app/assets/stylesheets/components/project_health_tag.sass
app/controllers/searches_controller.rb
app/helpers/application_helper.rb
app/models/project.rb
app/models/search.rb
app/views/components/_project_health_tags.html.slim
app/views/components/_project_order_dropdown.html.slim
app/views/pages/components/project_health_tag.html.slim
app/views/pages/docs/features/bugfix_forks.html.slim
app/views/projects/_project.html.slim
app/views/projects/show.html.slim
app/views/searches/show.html.slim
spec/controllers/searches_controller_spec.rb
spec/features/search_spec.rb
spec/models/project_spec.rb
spec/models/search_spec.rb

Following the addition of the backing logic for this via #377 this PR adds filtering of bugfix forks from search results by default, with the option to re-enable display via a button.
It also introduces a documentation page explaining the feature. Over the next weeks I want to add more of these, including a proper navigation item and sidebar navigation for the docs themselves.
This change highly increases top search result relevancy as explained in https://github.com/rubytoolbox/rubytoolbox/pull/377
When searching with the default of hidden bugfix forks yields no project results the controller redirects to the variant with forks enabled.
This PR also puts the new bugfix fork toggle as well as the previous custom project sorting dropdown (#360) into loading state to give some visual hint …

Filter bugfix forks from search results by default & allow to toggle display

---

app/models/project.rb
spec/models/project_spec.rb

I accidentally messed this up in up in ac9393bf56 (#360). The replacement of includes with left_outer_join did fix my search query sql problem, but now the nested associations are actually not eager loaded anymore, leading to performance hits on the search endpoint. The combination of includes and left outer join fixes that problem here.

Fix eager load for included assocations

---

app/jobs/project_update_job.rb
spec/jobs/project_update_job_spec.rb

Normally the project updating mechanism tries to detect the github repo from a gems link references.
The react-source gem references the upstream JS react  repo, which has an extremely large audience on github.  However it doesn't seem to have any affiliation with react itself. Since react's github popularity metrics (stars, forks) are much higher than the most popular ruby repo (at the time of  writing ;) this skews popularity scores, since the max stars and forks are considered for the overall popularity scoring. Hence, this gem is being prevented from linking against it referenced github repo.
To allow similar future tweaks this makes the actual blacklist a configurable array.

Allow blacklisting for linking github repos from gems

---

app/jobs/project_update_job.rb

Followup to #383, I overlooked a bugfix fork (see #377) of this gem since the query I was using excluded them.

Bugfix fork referencing react should also be excluded

---

app/helpers/component_helpers.rb
app/views/categories/show.html.slim
app/views/components/_bar_chart.html.slim
app/views/pages/components/bar_chart.html.slim
spec/features/category_display_spec.rb

Thanks to the charts utilities introduced in #388 this was now very simple. Fixes #126. I chose to only include the 10 top-scoring projects because especially on mobile for bigger categories the graph otherwise is too constrained. When using a custom project order (via #360) the chart is hidden.

Bring back category bar chart

---

app/assets/javascripts/charts/bar_chart.js
app/assets/stylesheets/application.css.sass
app/views/components/_bar_chart.html.slim

The category bar chart from #401 was too low on mobile, this makes the height flexible aspect ratio and an enclosing relative container as per chart.js docs

Improve mobile display of category bar chart

---

app/views/application/_search_form.html.slim
spec/features/search_spec.rb

Followup to #398. Across searches, the chosen display mode should remain persistent, but due to the way it's implemented if you pick a different display mode in the category display, then search from the top nav it would also use that display mode. While that might also have some merit it would break the new default of using the compact display mode in search by default (by enforcing full view), and I prefer consistent and expectable behaviour here. Also adds a missing feature spec that ensures this actuall works :)

Fix minor UI glitch in display mode selection

---

app/assets/stylesheets/components/hoverable_health_indicator.sass
app/helpers/component_helpers.rb
app/models/project.rb
app/models/project/health.rb
app/views/components/_hoverable_health_indicator.html.slim
app/views/components/_project_comparison.html.slim
app/views/components/_project_health_tags.html.slim
app/views/pages/components/project_health_tag.html.slim
spec/models/project/health_spec.rb
spec/models/project_spec.rb

This introduces project health indicators (see #355) to the new project comparison table view (via #398), since they can be very helpful to get an overview and were missing from the table. 
Since there's limited space on the table there is a new tiny badge that shows the color of the "worst" status. On hover it shows a popup that displays the actual health tags for that project.

Comparison table health indicators

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css.sass
app/controllers/comparisons_controller.rb
app/controllers/searches_controller.rb
app/helpers/application_helper.rb
app/helpers/component_helpers.rb
app/models/project.rb
app/views/comparisons/show.html.slim
app/views/components/_project.html.slim
app/views/components/project/_details_buttons.html.slim
app/views/components/project/_metrics.html.slim
app/views/layouts/application.html.slim
config/routes.rb
package.json
spec/controllers/comparisons_controller_spec.rb
spec/controllers/searches_controller_spec.rb
spec/features/comparisons_spec.rb
spec/models/project_spec.rb
spec/support/helpers/feature_spec_helpers.rb
yarn.lock

Following shortly to the new alternate display modes via #398 this PR adds a new feature that allows users to compare arbitrary projects using the usual project sorting / display modes, with the comparison pages being deep-linkable too.
The ability to compare arbitrary projects side by side came in in 3rd place in the [recent community survey](https://www.ruby-toolbox.com/blog/2018-12-04/survey-results) feature vote.
Since the top navigation became too crowded to fit all the content in the desktop breakpoint (~1024-1280px) I had to also tweak the responsiveness of the navigation a bit.
I'm not fully happy yet with how the display settings and consistent URL generation works at the moment, but I'll save that for a followup refactoring PR, it's tested and works, it just feels a bit brittle …

Project Comparisons

---

app/jobs/rubygem_downloads_persistence_job.rb
db/migrate/20190218131324_drop_download_stats_table_timestamps.rb
db/structure.sql

The timestamps do not provide much value on this table, and due to the large amount of records here creates a lot of extra storage needs, so dropping the timestamps.

Drop timestamp columns from download stats

---

app/models/rubygem_download_stat.rb
db/migrate/20190207133425_create_gem_trends_columns_and_calculation_trigger.rb
db/migrate/20190211104231_add_download_stats_indices.rb
db/structure.sql
spec/models/rubygem_download_stat_spec.rb

This follows up on #412 and adds additional stats to the absolute gem download numbers, calculated via postgresql triggers:
* `absolute_change_(week|month|year)`: The total number of downloads just in that timeframe (if previous record is there)
* `relative_change_(week|month|year)`: The percentage of all-time total downloads the timeframe's absolute downloads constitute
* `growth_change_(week|month|year)`: The difference between current relative change and the previous one in the timeframe
Those will be used for both project download history charts as well as trending project detection in the near future.
The actual historical data is also now restored into production, the process went like this:
* Recover historical daily download data from legacy Ruby Toolbox backups (starting late …

Gem download stats calculations

---

db/migrate/20190220133053_simplify_gem_trends_stats.rb
db/structure.sql
spec/models/rubygem_download_stat_spec.rb

Looks like I tried to solve too many problems at once via #424 by generating data that might eventually become useful upfront. Turns out populating the db with the historical data is putting it over capacity and just takes ages. Also, the size of https://data.ruby-toolbox.com data dumps will grow significantly, for no immediate benefit.
I was hoping to put up separate weekly/monthly/yearly trending projects up right from the start, but this is beginning to consume too much time and effort, so let's go back to keeping things pragmatic and just go with the monthly option for now (which is also used in #428), it can always be improved further later on.

Reduce pre-calculated gem stats to monthly

---

Gemfile
Gemfile.lock

It seems there are no references to this so it should be safe to remove.

Remove unused Timecop gem

---

.rubocop.yml

I think it's useful to order the rules alphabetically so that their are grouped according to category.

Order RuboCop config alphabetically

---

Gemfile
Gemfile.lock

Reverts rubytoolbox/rubytoolbox#437
Actually there is a test that uses it :boom:

Revert "Remove unused Timecop gem"

---

Gemfile

It seems this only only referenced from `spec/support/helpers/feature_spec_helpers.rb`.

Move retriable gem to `test` Bundler group

---

spec/rails_helper.rb

The tests are explicit about their type, so there is no need to infer it.

Remove unnecessary RSpec configuration option

---

app/views/welcome/home.html.slim

For some reason the production db takes ages to produce the simple counts used here (works just fine on the same dataset on my local machine), but I don't have the time right now to investigate. Appsignal does report however that the queries take a lot of time, so let's just drop this tiny sentence for now ("We list 2500 projects in 190 categories as well as 150300 Rubygems in total. Here are a few categories containing very popular Ruby libraries:") and investigate once I have time to look into it more closely.

Disable landing page stats temporarily, the counts are slow to calculate

---

app/assets/stylesheets/application.css.sass
app/assets/stylesheets/components/category_card.sass
app/controllers/trends_controller.rb
app/controllers/welcome_controller.rb
app/helpers/component_helpers.rb
app/models/category.rb
app/models/rubygem_download_stat.rb
app/views/components/_section_heading.html.slim
app/views/layouts/application.html.slim
app/views/pages/components/section_heading.html.slim
app/views/trends/show.html.slim
app/views/welcome/home.html.slim
config/routes.rb
db/migrate/20190226090240_add_index_on_categories_created_at.rb
db/migrate/20190226090403_add_categories_rank_index.rb
db/structure.sql
package.json
spec/controllers/trends_controller_spec.rb
spec/controllers/welcome_controller_spec.rb
spec/models/category_spec.rb
yarn.lock

This adds a new section to the landing page, featuring the 4 most recently added categories. I also added a little help badge referencing the newly added categories docs page (via #444) from the headings

New landing page section: Recently added categories

---

spec/features/styleguide_spec.rb
spec/jobs/rubygem_trends_job_spec.rb

* Fixes a flaky test that was only failing on sundays, coming from #449 
* Fixes a recently introduced failure in the styleguide check that's iterating over a list of dom nodes, and apparently capybara does not like that anymore since the recent upgrade via #463

Fix flaky tests

---

app/jobs/github_repo_update_job.rb
app/jobs/rubygem_update_job.rb
db/migrate/20190508190527_add_fetched_at_timestamps.rb
db/structure.sql
spec/integration/github_repo_update_spec.rb
spec/integration/rubygem_update_spec.rb

This adds a dedicated fetched at column on top of the regular rails updated_at for gems and repos to track when they've last been pulled from their source

Dedicated gems and repo remote fetch timestamp

---

app/models/rubygem/download_stat.rb
app/models/rubygem/trend.rb
spec/models/rubygem/trend_spec.rb

Fixes a bug that actually happened in production: A gem that is referenced from the weekly trends table has been yanked. Since we do not track yanked / gone gems the gem would have been deleted by the gem update job, however this recurringly failed due to the broken foreign key reference on the trends table via download stats. This PR fixes that issue.

Fix cascading deletion of a gem that was listed as trending

---

app/assets/stylesheets/components/project_release_history.sass
app/helpers/component_helpers.rb
app/jobs/rubygem_update_job.rb
app/models/project.rb
app/views/components/_project.html.slim
app/views/components/_project_release_history.html.slim
app/views/pages/components/project_release_history.html.slim
app/views/projects/show.html.slim
db/migrate/20190730194020_add_quarterly_releases_to_rubygems.rb
db/structure.sql
spec/jobs/rubygem_update_job_spec.rb

This PR adds a quarterly release activity heat map (and preparation of the underlying data) to projects that have rubygems to the project details, list and compact views in order to give a quick overview of historical and recent release activity of a project at a glance

Quarterly rubygem release activity heat map

---

app/views/components/_category_card.html.slim
spec/helpers/component_helpers_spec.rb

This addresses an unneccessary n+1 query on the landing page, where each featured category card was issuing a count statement for the project count to show on the footer despite the fact we're correctly pre-loading the collection anyway.

Remove unneccessary n+1 count query on category card

---

app/controllers/application_controller.rb
spec/controllers/application_controller_spec.rb

I get a bunch of exceptions for i.e. legacy / gone rss feed URLs not supporting the requested format. This changes things to handle unknown requested formats more gracefully by showing a 404 and not causing an exception notification every time...

Handle unknown format more gracefully / less noisy

---

app/helpers/application_helper.rb
app/views/welcome/home.html.slim
config/environments/production.rb
spec/helpers/application_helper_spec.rb

Following up on https://github.com/rubytoolbox/rubytoolbox/pull/630 which already reduced speed of the landing page quite a bit according to appsignal this should also bring in additional speed by reducing the number of queries made and partials rendered.
The landing page is mostly static anyway, so having this simple 10-minute rolling window expiring cache should already give a decent speed bump on that page even with this quite naive implementation

Enable simple in-memory time/release based cache for landing page

---

app/controllers/api/projects/comparisons_controller.rb
app/views/pages/docs/api/projects.html.slim
spec/requests/api/projects/compare_spec.rb

Minor followups to https://github.com/rubytoolbox/rubytoolbox/pull/598:
* Return explicit error when the requested projects are above the per-request limit to avoid silent ignores
* Add a bit more info on the API docs

API followups

---

app/services/github_client.rb
spec/cassettes/github/org_reference.yml
spec/cassettes/graphql/fails.yml
spec/cassettes/jnicklas/carrierwave.yml
spec/cassettes/rails/unknown_repo.yml
spec/integration/github_client_spec.rb
spec/services/github_client_spec.rb

Back on original implementation of the graphql API consumption code Github GraphQL API did not support querying for moved repos (i.e. jnicklas/carrierwave moved, but on REST API you'd get a proper redirect), so first we were pinging the regular HTML page to fetch the repo. However I strongly suspect this does nowadays cause https://github.com/rubytoolbox/rubytoolbox/issues/615 as we more often than not get an error response back from Github, maybe due to the anonymous requesting client or whatever.
This should bring the syncing to not erroneously cause the magic "UnknownRepo" exception any longer, leading to the dreaded repo gone red banner on ruby toolbox.

Remove obsolete github moved repo workaround that caused new issue

---

.circleci/config.yml
Gemfile
Gemfile.lock
README.md
package.json
spec/features/category_display_spec.rb
spec/features/comparisons_spec.rb
spec/features/docs_spec.rb
spec/features/search_spec.rb
spec/features/styleguide_spec.rb
spec/features/trending_spec.rb
spec/rails_helper.rb
yarn.lock

This PR adds integration with [percy](https://percy.io/) visual regression testing service.
The main reason behind this that I want to tackle upgrade to Rails 6 soon, and also upgrade some of the frontend dependencies, so if anything goes horribly wrong this should be helpful in finding any regressions before they hit production.

Integrate percy.io visual regression test service

---

.circleci/config.yml
Gemfile

The docker image is now available, the hack from #639 can go

Drop CI workaround from #639

---

app/assets/javascripts/charts/bar_chart.js
app/assets/javascripts/charts/line_chart.js
app/assets/javascripts/charts/rubygem_download_chart.js
app/views/pages/components/landing_feature.html.slim

The automated UI regression tests introduced via #657 were giving a bunch of false positives on the components example pages - [example can be found here](https://percy.io/rubytoolbox/rubytoolbox/builds/5459155)
One of them was a randomly displayed amount of lorem ipsum, fixed that to be deterministic.
The other part was the chart.js showup animation being in different stages of the animation. I considered waiting for animations to finish or such, but ultimately I just decided to disable them altogether since I believe their presence actually makes the pages appear to load slower then they are, so that should resolve that.

Fix UI regression tests false positives

---

Gemfile
Gemfile.lock
config/application.rb
spec/requests/api/projects/compare_spec.rb

Closes #666
If you're open to it, this would allow other webpages to request things from the API, such that people could build things like chrome plugins or other sites that can take advantage of the great information living in the rubytoolbox!

Allow CORS requests on API endpoints

---

app/jobs/github_repo_update_job.rb
app/models/github/readme.rb
app/models/github_repo.rb
app/services/github_client.rb
db/migrate/20200830205823_create_github_readmes.rb
db/structure.sql
spec/cassettes/full-project-sync-from-gem.yml
spec/cassettes/full-project-sync-from-github.yml
spec/cassettes/github/readme/existing.yml
spec/cassettes/github/readme/moved.yml
spec/cassettes/github/readme/unknown.yml
spec/cassettes/rails/rails.yml
spec/integration/github_client_spec.rb
spec/integration/github_repo_update_spec.rb
spec/jobs/github_repo_update_job_spec.rb

This PR adds syncing of repository READMEs from Github into the toolbox database. 
Since fetching that via graphql is highly limited when compared to the [v3 api for this](https://docs.github.com/en/rest/reference/repos#get-a-repository-readme) (most notably no automatic default branch + default readme filename detection on generic request) this uses the regular REST API
The READMEs get persisted into a dedicated db table since they can get quite big and for the majority of views there is no need to send this data over the wire from postgres to the app and put it into ruby objects just to toss it away immediately again.
Display will be added later, with this added the syncing of the data can already get going in the background.

Repo README syncing

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/readme.sass
app/helpers/component_helpers.rb
app/models/github/readme.rb
app/models/github_repo.rb
app/models/project.rb
app/views/components/project/_readme.html.slim
app/views/pages/components/project_readme.html.slim
app/views/projects/show.html.slim
spec/features/project_spec.rb
spec/models/github/readme_spec.rb
spec/models/github_repo_spec.rb
spec/models/project_spec.rb

Following up on yesterday's #730 this adds display of the newly synced project READMEs to project details pages
Still pending:

README display

---

app/views/trends/show.html.slim
spec/features/trending_spec.rb

I am trying improve the ux with buttons of navigation when finish the trends page, but i am not know this slim, I think we can improve how is it write, so if you can help-me, pls do your review. 
Before
Now

add buttons of navigations in trends page

---

app/jobs/github_repo_update_job.rb
app/services/github_client.rb
spec/integration/github_client_spec.rb
spec/jobs/github_repo_update_job_spec.rb

Followup to #731 noticed while doing some checkups before publishing #769 - turns out since 404 and 304 cache hit were both returning `nil` when a readme was stored fine but didn't change until next sync it was removed accidentally again from the database :facepalm: 
This should fix that. Not very proud about the use of exceptions for control flow here, but after evaluating a bit my options honestly I could not be bothered coming up with something more elegant right now, iet's just get it back to full function for now...

Fix accidental removal of stored readme on cache hit

---

app/assets/stylesheets/application.css.sass
package.json
yarn.lock

Followup to #731, this adds syntax highlighting to code blocks in README display:
The code blocks fall out of GitHub's api properly wrapped in highlight classes, however the actual css schema seems to from some custom / internal highlighter called "prettylights", see https://github.com/github/pages-gem/issues/160 and uses it's own css classes that are not compatible with common CSS classes from rouge or pygments. Luckily I found [this](https://github.com/primer/github-syntax-light) helpful npm package that ships the neccessary CSS classes, so things look a bit nicer now

Add syntax highlighting for readme code blocks

---

app/assets/stylesheets/components/readme.sass
app/views/components/project/_readme.html.slim

Fixes scroll jump issue in chrome when viewing readme and hovering sponsor logo #757
This is very weird. Doesn't happen on firefox. Change from span to div fixed it. I actually tried to reproduce this in an isolated codepen, but no idea. It definetely has to do with the sticky positioning of the "Project Readme" label, if I take that out it goes away. Maybe it has to do with the headroom-js-driven hiding main nav bar together. Regardless, with a div it works fine so ¯\_(ツ)_/¯

Fix chrome scroll jump issue

---

app/jobs/project_search_index_job.rb
app/jobs/project_update_job.rb
app/services/meili_search.rb
spec/jobs/project_search_index_job_spec.rb
spec/jobs/project_update_job_spec.rb
spec/services/meili_search_spec.rb

The current search on the site is rather slow and I'm currently in the process of speeding it up by converting the search indexing to [MeiliSearch](https://www.meilisearch.com/). I've done some initial prototyping on this recently and the results using that for the search and then fetching the resulting projects from Postgres looked very promising, and this code is the beginning of porting the prototype code into actually converting this over.

Add integration with MeiliSearch

---

app/models/search.rb
app/services/meili_search.rb
config/brakeman.ignore
spec/models/search_spec.rb
spec/services/meili_search_spec.rb

This is a followup to #831 which adds logic to perform project search queries against the external MeiliSearch index instead of using Postgres search. 
When results are received in the shape of permalinks from the search index, subsequently the corresponding projects are fetched once again from postgres, which in my tests was much much quicker.
As I'm still experimenting with this and I'd like to verify that my prior performance tests actually hold true this ships this feature behind a feature flag to enable some additional testing of this before I then hopefully move on to fully replace the existing search code with this (and throwing in some additional specs and refactoring the not-yet-optimal order query stuff)

Allow to actually search against new search index

---

app/models/project.rb

Followup to https://github.com/rubytoolbox/rubytoolbox/pull/845#issuecomment-787196925, the previous code led to all things on the scope being loaded when using pagination, instead of only the current page

Scope performance fix when bugfix forks are included

---

app/views/pages/components/landing_hero.html.slim
spec/jobs/rubygem_downloads_persistence_job_spec.rb
spec/jobs/rubygem_trends_job_spec.rb
spec/support/factories.rb

We get visual regression checks from Percy on CI runs, which is nice. However, since some of the dates used in the underlying specs that make the screenshots were dynamic every single CI run needed manual approval. This should hopefully resolve that and also not introduce any other issues either :)

Prevent date drift in UI snapshots for visual regression tests

---

Gemfile
Gemfile.lock
app/jobs/rubygem_update_job.rb
app/models/rubygem.rb
app/models/rubygem_dependency.rb
db/migrate/20210228234343_create_rubygem_dependencies.rb
db/structure.sql
spec/jobs/rubygem_update_job_spec.rb
spec/models/rubygem_dependency_spec.rb
spec/models/rubygem_spec.rb
spec/rails_helper.rb

This PR adds sync of rubygem dependencies (runtime and development) into the database. We used to have this on the old site, it's time to bring it back.
Display of the dependencies, ideally including health metrics indicator, will come in a followup, this is for now just about getting the data into the database.

Sync gem dependencies

---

spec/features/category_display_spec.rb
spec/features/search_spec.rb
spec/support/factories.rb

Didn't catch all of them in https://github.com/rubytoolbox/rubytoolbox/pull/847 it seems. Again, some dynamic dates from factories led to this, i.e. see https://percy.io/rubytoolbox/rubytoolbox/builds/9650228 for the build of https://github.com/rubytoolbox/rubytoolbox/pull/855
Hopefully I managed to catch all of them now.

Fix more false positives in visual regression tests

---

.github/workflows/ci.yml
README.md

I upgraded the production db the site runs on to postgres 13, the CI should match that. To prevent surprises for people trying to run locally I also mentioned the version on the README for good measure.

Bump CI version of Postgres (and update README)

---

spec/features/comparisons_spec.rb
spec/features/search_spec.rb

Another round of fixing moving dates in visual regression test screenshots that are being captured following https://github.com/rubytoolbox/rubytoolbox/pull/856 and https://github.com/rubytoolbox/rubytoolbox/pull/847, again it's due to some relative dates being defined (and then rendered) in the test setups. Gotta catch 'em all...

Fix more visual regression test drift

---

Gemfile
app/assets/stylesheets/application.css.sass
package.json
yarn.lock

This PR loosens version restrictions on the package json significantly, mostly allowing any new versions where applicable. A cursory local UI and features check indicates everything is still fine, let's see what visual regression tests report.

Loosen yarn package version constraints and bump things to latest

---

Gemfile
Gemfile.lock

While going through the depfu dashboard I noticed some dependencies had upgrades available but could not be upgraded due to Gemfile version constraints. I loosened (or rather dropped) those and upgraded all the things

Loosen pinned gem version constraints and bump related gems

---

app/assets/stylesheets/components/project.sass
app/controllers/projects_controller.rb
app/models/rubygem_dependency.rb
app/views/projects/show.html.slim
config/brakeman.ignore
spec/controllers/projects_controller_spec.rb
spec/features/project_spec.rb
spec/models/rubygem_dependency_spec.rb

Based upon the data we started syncing via https://github.com/rubytoolbox/rubytoolbox/pull/854 this adds display of rubygem dependencies to project details pages, including a health badge:
Some followups should take place:
* This uses the layout introduced for the project README a few months ago, however it did not fully fit the use case because that one wraps the main column in a bulma `.content` block, meant for formatted / markdown content. This should be broken out into a dedicated meta thingy for this emerging layout pattern we have here with a section title on the side and the main content next to it, which should also not be named `readme` anymore (and then the change here to the readme feature spec can be rolled back properly too again :)
* Handle the no dependencies for this type …

Add display of rubygem dependencies to projects

---

app/views/projects/show.html.slim

Small followup to #891 - when a gem is yanked (or never existed) yet is declared as a dependency, the view code crashed before.
This small adjustment adds a fallback to the template that ensures the dependency is still rendered:

Fallback if a gem declared as dependency doesn't exist

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
config/initializers/high_voltage.rb
config/routes.rb
spec/controllers/application_controller_spec.rb
spec/controllers/pages_controller_spec.rb
spec/features/docs_spec.rb

Since HighVoltage raises a routing error by default and this causes a bit of noise on our Appsignal exception tracking this PR ramps up the high voltage integration to use an explicitly declared controller (instead of the implicit one) and adds an explicit rendering of 404 pages as per https://github.com/thoughtbot/high_voltage/issues/23#issuecomment-245631978

Handle gracefully requests for unknown docs pages

---

db/migrate/20210531193907_add_missing_indices_to_rubygem_dependencies.rb
db/migrate/20210531194507_add_missing_index_on_projects_github_repo_path.rb
db/structure.sql

🔗 Follows #854 and #891
This adds missing indices on the two gem name reference columns which apparently I forgot the first time around 😊 🤦
Also adds an index on `projects.github_repo_path` because according to Heroku postgres stats we're calling this a bunch but didn't have the index in place yet.

Add missing indices to rubygem dependencies table

---

app/assets/stylesheets/components/project.sass
app/controllers/projects_controller.rb
app/models/project.rb
app/models/rubygem.rb
app/models/rubygem_dependency.rb
app/views/components/project/_metric.html.slim
app/views/pages/components/project_comparison.html.slim
app/views/projects/reverse_dependencies.html.slim
config/routes.rb
spec/features/project_spec.rb
spec/models/project_spec.rb
spec/models/rubygem_dependency_spec.rb

Based on the dependency data added via #854 for #891 as well as #938 to aid with feature-testing this, this makes reverse dependencies of a project browsable.
There's still some followup work to be done, but that can take place in a followup PR:
* Add custom sorting
* Clean up the shared view and controller logic for the display mode and sorting stuff, which was for now just mostly copied over from the search feature

Display reverse dependencies

---

.bundler-audit.yml

See also https://github.com/sidekiq/sidekiq/discussions/6039
I also tried switching from redis enterprise cloud to heroku's redis, however that requires [to configure the connection to not verify SSL](https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-ruby) which I also don't want to do as, regardless of their explanation about self signed certificates. I do wonder though why those self signed cert's cannot be added to the dyno cert chain instead of completely deactivating SSL verification, but I suppose there's reasons.

Ignore sidekiq CVE-2023-26141 until we can upgrade to redis 7

---

Gemfile.lock
spec/rails_helper.rb

Resolves an issue that made the build fail from Chrome 120+. Ref: https://github.com/SeleniumHQ/selenium/issues/13112

Re-configure selenium headless chrome

---

Procfile
app/controllers/database/exports_controller.rb
app/jobs/database/store_selective_export_job.rb
app/models/database/export.rb
app/models/database/selective_export.rb
app/services/cron.rb
config/brakeman.ignore
config/routes.rb
lib/tasks/release.rake
spec/controllers/database/exports_controller_spec.rb
spec/jobs/database/store_selective_export_job_spec.rb
spec/models/database/export_spec.rb
spec/models/database/selective_export_spec.rb
spec/services/cron_spec.rb

This follows #1300 and #1301 for #1205.
* Generate the selective database exports via cron every 4 hours via a background job
* Introduce an endpoint that redirects to the latest export

Generate selective exports periodically and allow access via an endpoint

---

Gemfile
app/jobs/rubygem_advisories_sync_job.rb
app/models/project.rb
app/models/rubygem.rb
app/models/rubygem/advisory.rb
db/migrate/20240607091753_create_rubygem_advisories.rb
db/structure.sql
spec/jobs/rubygem_advisories_sync_job_spec.rb
spec/models/project_spec.rb
spec/models/rubygem/advisory_spec.rb
spec/models/rubygem_spec.rb

This is for #1196 and adds a job that utilizes bundler-audit to sync https://github.com/rubysec/ruby-advisory-db into our own database, for later displaying on the site itself.
On a side note, I am developing this feature using codespaces, giving https://www.ruby-toolbox.com/blog/2024-05-31/devcontainers a spin in realistic conditions to figure out any quirks and issues and find out if it's fully functional as a work environment as it is or whether it needs further improvements

Import ruby-advisory-db advisories

---

app/models/database/selective_export.rb
spec/models/database/selective_export_spec.rb

Follows https://github.com/rubytoolbox/rubytoolbox/pull/1352, I forgot to actually declare the scope to be exported as well :facepalm:

Actually include the advisories in selective export

---

db/migrate/20240628122603_change_downloads_column_type_to_bigint.rb
db/migrate/20240628122914_adjust_trends_trigger_to_bigint.rb
db/structure.sql

The rubygem sync got stuck on the bundler gem because it's download count exceeded the integer column type limit :rocket: 
So, this adjusts the relevant column types accordingly to make some space for more downloads, and adjusts the dependent trigger function for the trends calculation accordingly to take a bigint as the argument as well.

Convert rubygem downloads count to bigint

---

db/migrate/20240628122603_change_downloads_column_type_to_bigint.rb
db/migrate/20240628122914_adjust_trends_trigger_to_bigint.rb
db/structure.sql

A new take on https://github.com/rubytoolbox/rubytoolbox/pull/1364 after #1365 - especially the download stats table is too huge for this to work with the naive approach, should've thought of that :facepalm:

Safer approach at convert rubygem downloads count to bigint

---

Gemfile
Gemfile.lock

Can you believe it, it's finally possible to switch to RESP3 on redis cloud :tada:  So [this saga](https://github.com/sidekiq/sidekiq/issues/5594) can finally find closure

Finally bump sidekiq to 7+

---

app/services/github_client/repository_data.rb
spec/services/github_client/repository_data_spec.rb

This popped up on Appsignal. The field is declared as non-nullable on GraphQL, but Github actually crashes with a 500 when you open https://github.com/grosser/open_id_authentication/commits/master/, and we get a null value for authoredDate from GraphQL despite the schema saying otherwise, so I guess we just work around this to ensure the updates still work and we don't get error notifications

Fix error when github returns null on a non-nullable graphql property

---

app/frontend/entrypoints/application.js
app/frontend/entrypoints/application.sass
app/frontend/javascript/fix_readme_overflow.js
app/views/layouts/application.html.slim
spec/features/mobile_navigation_spec.rb

This fixes two issues when opening the site on mobile:
1. The navbar breaks out of the viewport width, hiding or at least partially obstructing the burger
The problem here is that bulma doesn't really seem to have a way to add another icon (like we have here in the search button) into the mobile navbar + burger. The adjustment I made feels a bit hacky still, but I wanted to make it work within what Bulma provides. An alternative would be to just create a custom layout for this, probably best using CSS grid
2. When opening a project page that has a wide table in their readme (like https://www.ruby-toolbox.com/projects/rein) the table was also breaking out of the viewport to the right
The problem is we get the rendered html from Github as it is, and there's no container to declare CSS …

Fix mobile UI width glitches
