rubytoolbox/rubytoolbox

- config/environments/production.rb
Fixes rubytoolbox/rubytoolbox#18
> Enabled HSTS for rack-ssl-enforcer

- app/helpers/application_helper.rb
- app/models/category.rb
- app/models/project.rb
- app/views/categories/show.html.slim
- app/views/projects/_metric.html.slim
- spec/helpers/application_helper_spec.rb
- spec/models/project_spec.rb
Actually display the description and downloads added via #47 and #52 on the html output :)
> Display actual gem info

- app/models/project.rb
- app/views/projects/_metrics.html.slim
Tiny followup to #70: Also show the current gem version number.
> Incorporate current gem version into UI

- app/views/layouts/application.html.slim
- app/views/searches/show.html.slim
:man_facepalming: :woman_facepalming: :crying_cat_face: 
Followup to #84
> Make the search button actually functional

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css.sass
- app/blog_posts/2017-12-01-example-post.md
- app/blog_posts/2018-01-12-another-post.md
- app/controllers/blog_controller.rb
- app/helpers/application_helper.rb
- app/models/blog.rb
- app/views/blog/index.html.slim
- app/views/blog/index.rss.builder
- app/views/blog/show.html.slim
- app/views/layouts/application.html.slim
- config/routes.rb
- spec/controllers/blog_controller_spec.rb
- spec/fixtures/blog_posts/2017-12-01-example-post.md
- spec/fixtures/blog_posts/2018-01-12-another-post.md
- spec/models/blog_spec.rb
- spec/routes/blog_routes_spec.rb
This adds a very simple, static-markdown-file-backed, memory-cached blog to the site.
Todo:
Fixes #86
> Project Blog

- app/blog_posts/2017-12-01-example-post.md
- app/blog_posts/2018-01-12-another-post.md
- app/blog_posts/2018-02-01-lets-push-things-forward.md
- app/views/blog/show.html.slim
- app/views/welcome/home.html.slim
> Relaunch announcement blog post

- README.md
> README note

- app/blog_posts/2018-02-01-lets-push-things-forward.md
Hi, and thank you for this gift!
This PR is a tiny tiny blog post edit.
Cheers!
> Blog post content: tiny copy-edits

- README.md
This is a followup to #127 and fixes #82
> README expansions

- app/views/projects/_metrics.html.slim
Changed "Depencencies" to "Dependencies"
> Fix Spelling Error

- app/blog_posts/2018-11-05-community-survey.md
- app/views/layouts/application.html.slim
Announcement for https://survey-2018.ruby-toolbox.com/
> Add community survey post and banner

- app/views/layouts/application.html.slim
Originally introduced in #313. Now that the community survey is finished it can be removed again :)
> Drop community survey announcement banner

- app/assets/stylesheets/application.css.sass
- app/blog_posts/2018-12-04-survey-results.md
> Add survey results blog post

- app/assets/stylesheets/application.css.sass
- app/blog_posts/2018-11-05-community-survey.md
- app/blog_posts/2018-12-04-survey-results.md
Some minor cleanup followups to #329
> Survey cleanups

- app/graphql-queries/github/repo.graphql
- app/jobs/github_repo_update_job.rb
- app/services/github_client.rb
- app/services/github_client/repository_data.rb
- db/migrate/20181205134522_add_topics_and_code_of_conduct_to_github_repos.rb
- db/structure.sql
- spec/cassettes/full-project-sync-from-gem.yml
- spec/cassettes/full-project-sync-from-github.yml
- spec/cassettes/graphql/carrierwave.yml
- spec/cassettes/graphql/empty.yml
- spec/cassettes/graphql/fails.yml
- spec/cassettes/graphql/rails.yml
- spec/cassettes/rails/rails.yml
- spec/fixtures/graphql_responses/github/rails.json
- spec/integration/github_client_spec.rb
- spec/jobs/github_repo_update_job_spec.rb
This code of conduct and repo topics to the syncing from github.
Also contains a cleanup which switches the graphql query itself to use variables instead of injecting them via erb.
> Sync repo topics and code of conduct from Github

- app/controllers/webhooks/github_controller.rb
> Fix authenticitiy token blunder on webhook endpoint

- app/blog_posts/2018-12-14-project-health-indicators.md
Followup to #355, shipping in a separate PR to see it run in production for a while before making bold announcements only to realize it's broken :)
> Announcement for project health indicators

- app/blog_posts/2019-01-09-project-sorting.md
For #360, as usual in a followup PR once the dust has settled
> Announcement post for project sorting

- app/blog_posts/2019-01-09-new-landing-page.md
Announcement blog post for #335, as usual in a followup PR to avoid promoting broken stuff :fire:
> Landing page announcement post

- .circleci/config.yml
- .foreman
- Gemfile
- Gemfile.lock
- Procfile
- README.md
I've had a bunch of issues with the Toolbox builds on Travis recently, so let's try Circle instead. From my preliminary testing the builds seem more stable and are definetely faster to complete. The flexible workflow definitions also seem nice.
> Build with circle CI

- app/blog_posts/2019-01-31-alternate-project-display-modes.md
> Blog post for project display modes

- app/blog_posts/2019-02-14-project-comparisons.md
- app/views/comparisons/show.html.slim
The usual separate post-deploy release announcement, this time for #408
> Project Comparisons announcement post

- Gemfile
- Gemfile.lock
- config/routes.rb
A tiny change that adds https://github.com/ankane/pghero in the dev environment
> Add pghero gem in development env

- app/blog_posts/2019-02-25-historical-gem-download-charts.md
- app/views/pages/docs/features/historical_rubygem_download_data.html.slim
- app/views/pages/docs/features/production_database_exports.html.slim
- config/locales/en.yml
Announcement post and docs page for #428
> Download Charts announcement

- app/models/docs.rb
- app/views/pages/docs/features/categories.html.slim
- app/views/pages/docs/guides/guide_for_library_maintainers.html.slim
- config/locales/en.yml
- spec/models/docs_spec.rb
Adds two new documentation pages
> Docs: Guide for project maintainers and categories feature description

- app/controllers/welcome_controller.rb
- app/helpers/component_helpers.rb
- app/models/category.rb
- app/views/components/_section_heading.html.slim
- app/views/pages/components/section_heading.html.slim
- app/views/welcome/home.html.slim
- db/migrate/20190226090240_add_index_on_categories_created_at.rb
- db/migrate/20190226090403_add_categories_rank_index.rb
- db/structure.sql
- spec/controllers/welcome_controller_spec.rb
- spec/models/category_spec.rb
This is so embarassing. Brings back #446 sans #440
> Landing page: New categories retry

- app/blog_posts/2019-02-28-trending-projects.md
- app/views/pages/docs/features/trending_projects.html.slim
- app/views/trends/show.html.slim
- config/locales/en.yml
Announcement and docs for #449
> Trending projects announcement

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
As per https://github.com/flavorjones/chromedriver-helper/issues/83
> Move to webdrivers gem in favor of deprecated chromedriver-helper

- app/blog_posts/2020-01-09-rubygem-release-heatmaps.md
Finally, the announcement for #548
> Release heatmaps announcement post

- .rubocop.yml
- app/jobs/rubygem_update_job.rb
- app/models/category.rb
- app/models/project.rb
Post-upgrade steps:
* Opt-in to new rubocop cops
* Address deprecation warning from PgSearch
> Manual gem upgrades

- README.md
- app/blog_posts/2020-04-29-api-for-project-data.md
- app/views/pages/docs/api/projects.html.slim
Also: Update README header to mirror landing page text
> Minor tweaks to API docs and announcement post

- app/views/trends/_pagination.html.slim
- app/views/trends/show.html.slim
> Move out duplicated trends pagination nav to partial

- app/blog_posts/2020-10-30-project-readmes.md
> Add announcement post for project READMEs to the blog

- app/blog_posts/2021-03-19-search-speed-improvements.md
> Add blog post regarding search improvements

- yarn.lock
Following https://github.com/rubytoolbox/rubytoolbox/pull/870 this also upgrades all yarn dependencies to latest. Following this I will also enable yarn upgrades via depfu
> Update all yarn dependencies

- app/blog_posts/2021-06-29-rubygem-dependencies.md
> Add blog post regarding gem dependencies display

- app/jobs/rubygem_backfill_stats_job.rb
- spec/jobs/rubygem_backfill_stats_job_spec.rb
And that's why it's good to also always have an integration test... Followup to #1258
> Fix wrong attribute name used in #1258 😊

- app/blog_posts/2024-05-01-15-years-of-ruby-toolbox.md
> :cake: 15 years blog post

- app/blog_posts/2024-05-31-devcontainers.md
- app/jobs/database/store_selective_export_job.rb
- app/models/database/export.rb
- spec/jobs/database/store_selective_export_job_spec.rb
- spec/models/database/export_spec.rb
> Purge older partial db dumps
